# Generated by Django 3.2.8 on 2021-11-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('tag', models.CharField(blank=True, choices=[('BUG', 'bug'), ('IMPROVE', 'improve'), ('TASK', 'task')], max_length=32)),
                ('priority', models.CharField(blank=True, choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], max_length=32)),
                ('status', models.CharField(blank=True, choices=[('TODO', 'todo'), ('DOING', 'doing'), ('DONE', 'done')], max_length=32)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('type', models.CharField(blank=True, choices=[('BACKEND', 'back-end'), ('FRONTEND', 'front-end'), ('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=32)),
            ],
        ),
    ]
