# Generated by Django 3.2.8 on 2021-10-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211021_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
    ]
