# Generated by Django 3.2.8 on 2021-10-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211021_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_user_id',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='issue_id',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='assignee_user_id',
            new_name='assignee_user',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='author_user_id',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='author_user_id',
            new_name='author_user',
        ),
    ]
