# Generated by Django 3.2.8 on 2021-10-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211021_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('BACKEND', 'back-end'), ('FRONTEND', 'front-end'), ('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=32),
        ),
    ]
